-- Migration 00015: Clinical image analysis infrastructure
--
-- Creates clinical_images table for dermatology photography and
-- image_analysis table for provider-independent analysis results.
--
-- The existing medical_images table (00005) is preserved for
-- radiology-style imaging (x-ray, MRI, CT) linked to lab_reports.
-- This new clinical_images table is designed for clinical photography
-- and AI-assisted dermatology image analysis.
--
-- All new columns are nullable where appropriate to preserve
-- backward compatibility.

BEGIN;

------------------------------------------------------------
-- 1. clinical_images
------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.clinical_images (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  patient_id      uuid NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
  encounter_id    uuid REFERENCES public.encounters(id) ON DELETE SET NULL,
  organization_id uuid REFERENCES public.organizations(id),
  clinic_id       uuid REFERENCES public.clinics(id),
  storage_path    text NOT NULL,
  file_name       text NOT NULL,
  file_size       bigint,
  content_type    text,
  body_area       text,
  diagnosis       text,
  notes           text,
  created_by      uuid NOT NULL REFERENCES auth.users(id),
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_clinical_images_patient
  ON public.clinical_images(patient_id);

CREATE INDEX IF NOT EXISTS idx_clinical_images_encounter
  ON public.clinical_images(encounter_id);

CREATE INDEX IF NOT EXISTS idx_clinical_images_org
  ON public.clinical_images(organization_id);

CREATE INDEX IF NOT EXISTS idx_clinical_images_created_at
  ON public.clinical_images(patient_id, created_at DESC);

ALTER TABLE public.clinical_images ENABLE ROW LEVEL SECURITY;

CREATE POLICY clinical_images_select ON public.clinical_images FOR SELECT
  USING (public.get_user_role(auth.uid()) IN ('doctor', 'admin'));

CREATE POLICY clinical_images_insert ON public.clinical_images FOR INSERT
  WITH CHECK (public.get_user_role(auth.uid()) IN ('doctor', 'admin'));

CREATE POLICY clinical_images_delete ON public.clinical_images FOR DELETE
  USING (public.get_user_role(auth.uid()) IN ('doctor', 'admin'));

CREATE TRIGGER set_clinical_images_updated_at
  BEFORE UPDATE ON public.clinical_images
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

GRANT SELECT, INSERT, DELETE ON public.clinical_images TO authenticated;

------------------------------------------------------------
-- 2. image_analysis
------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.image_analysis (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  clinical_image_id uuid NOT NULL REFERENCES public.clinical_images(id) ON DELETE CASCADE,
  patient_id      uuid NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
  organization_id uuid REFERENCES public.organizations(id),
  status          text NOT NULL DEFAULT 'pending'
                    CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
  provider        text NOT NULL,
  model           text,
  result          jsonb,
  processing_time_ms integer,
  error_message   text,
  created_by      uuid NOT NULL REFERENCES auth.users(id),
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_image_analysis_image
  ON public.image_analysis(clinical_image_id);

CREATE INDEX IF NOT EXISTS idx_image_analysis_patient
  ON public.image_analysis(patient_id);

CREATE INDEX IF NOT EXISTS idx_image_analysis_status
  ON public.image_analysis(patient_id, status, created_at DESC);

ALTER TABLE public.image_analysis ENABLE ROW LEVEL SECURITY;

CREATE POLICY image_analysis_select ON public.image_analysis FOR SELECT
  USING (public.get_user_role(auth.uid()) IN ('doctor', 'admin'));

CREATE POLICY image_analysis_insert ON public.image_analysis FOR INSERT
  WITH CHECK (public.get_user_role(auth.uid()) IN ('doctor', 'admin'));

CREATE POLICY image_analysis_update ON public.image_analysis FOR UPDATE
  USING (public.get_user_role(auth.uid()) IN ('doctor', 'admin'))
  WITH CHECK (true);

CREATE TRIGGER set_image_analysis_updated_at
  BEFORE UPDATE ON public.image_analysis
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

GRANT SELECT, INSERT, UPDATE ON public.image_analysis TO authenticated;

------------------------------------------------------------
-- 3. clinical-images Storage Bucket
--
-- Creates a private Supabase Storage bucket for clinical
-- photography with RLS-backed access policies.
--
-- The bucket is PRIVATE: images are only accessible via
-- authenticated signed URLs generated by the application.
------------------------------------------------------------

-- Create the bucket (idempotent via IF NOT EXISTS semantics
-- baked into storage.create_bucket in newer Supabase versions)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'clinical-images',
  'clinical-images',
  false,
  10485760,  -- 10 MB max per file
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/dicom']
)
ON CONFLICT (id) DO NOTHING;

-- RLS policies on storage.objects for the clinical-images bucket
CREATE POLICY clinical_images_storage_select ON storage.objects FOR SELECT
  USING (bucket_id = 'clinical-images' AND auth.role() = 'authenticated');

CREATE POLICY clinical_images_storage_insert ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'clinical-images' AND auth.role() = 'authenticated');

CREATE POLICY clinical_images_storage_delete ON storage.objects FOR DELETE
  USING (bucket_id = 'clinical-images' AND auth.role() = 'authenticated');

COMMIT;